version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: sleep $(( ( RANDOM % 1000 )  + 2 ))
workflows:
  run-jobs:
    jobs:
      - build
    # triggers: #use the triggers key to indicate a scheduled build
    #   - schedule:
    #       cron: "0 0 * * *" # use cron syntax to set the schedule
    #       filters:
    #         branches:
    #           only:
    #             - main

